spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password-nope
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true # Pour que le data.sql passe APRÈS la création du schema par JPA